### ISSUE TITLE
io.toolisticon.cute.impl.CompileTest should always check compileTestBuilder.compilationShouldFail()

### ISSUE THREAD

**Issue by cvgaviao** [toolisticon/cute#64]
I have an issue where my failed test should pass but it is not.
I've created an annotation that has an attribute `withInterface` of type `Class<? extends ApiService>` 

I've then created a test that ensures that the compilation will fail when we do not use the right interface.
```
  @Test
  void test_processingShouldntSucceesWithPlainInterfacesNotExtendingApiService() {
    compileTestBuilder
                     .addSources("api_service/TestcaseInvalidUseWithInterfaceNotExtendingApiService.java")
                      .compilationShouldFail()
                      .executeTest();
  }
  ```
  But this test is failing.
  I think that is because the method from `CompileTest` below: 
  ```
      void checkIfProcessorsHaveBeenApplied(DiagnosticCollector<JavaFileObject> diagnostics) {

        Set<String> messages = CompileTestUtilities.getMessages(diagnostics, Diagnostic.Kind.NOTE);

        outer:
        for (AnnotationProcessorWrapper processor : compileTestConfiguration.getWrappedProcessors()) {

            for (String message : messages) {
                if (message.equals(processor.getProcessorWasAppliedMessage())) {
                    continue outer;
                }
            }

            throw new FailingAssertionException(Constants.Messages.MESSAGE_PROCESSOR_HASNT_BEEN_APPLIED.produceMessage(processor.getWrappedProcessor().getClass().getCanonicalName(), processor.getSupportedAnnotationTypes()));

        }
        ```
        
        Perhaps would be possible to verify the compileTestBuilder.compilationShouldFail() before throw FailingAssertionException even if the processor was not called ?

**Comment by tobiasstamann** [comment]
Hi,

I added that check by intent. I used googles compile testing framework before and got into the situation that i expected a successful outcome but encountered the situation that the annotation processor wasn't applied at all.

So a check validates that all configured annotation processors are really used to prevent false positives.

So  please remove the annotation processors from unit test configuration that you don't expect to be called, since they doesn't change test outcome in any way.

It may also be that your testcase source file doesn't trigger the processor. So please check if the processor mentioned in the MESSAGE_PROCESSOR_HASNT_BEEN_APPLIED log statement is the one that you expect to trigger the compilation to fail.
In this case you should check if your test souce file and the annotation processor are configured correctly.

**Comment by tobiasstamann** [comment]
Can you also post the common initialisation part of the compileTestBuilder?

**Comment by cvgaviao** [comment]
> So please remove the annotation processors from unit test configuration that you don't expect to be called, since they doesn't change test outcome in any way.

Well, I use only one compileTestBuilder for the entire test class. Do you mean that for this test method I  would need to create one specific compileTestBuilder for it? 

> Can you also post the common initialization part of the compileTestBuilder?

```
  CompileTestBuilder.CompilationTestBuilder compileTestBuilder = CompileTestBuilder
                                                                                   .compilationTest()
                                                                                   .addProcessors(ApiServiceProcessor.class);
```
and that is the result I'm getting:

```
java.lang.AssertionError: Annotation processor br.com.c8tech.hawkx.dev.apt.processors.http.ApiServiceProcessor hasn't been called! Please check that there's at least one source file using an annotation supported by the processor: [br.com.c8tech.hawkx.annotations.http.ApiServiceTag]

-------------------------------
-- ERROR MESSAGES: 
-------------------------------
[1]'/api_service/TestcaseInvalidUseWithInterfaceNotExtendingApiService.java:6: error: incompatible types: java.lang.Class<br.com.c8tech.hawkx.dev.apt.processors.tests.apiservices.TestSpiInterface> cannot be converted to java.lang.Class<? extends br.com.c8tech.hawkx.services.http.ApiService>
@ApiServiceTag(id = "x", withInterface = TestSpiInterface.class)
                                                         ^'

-------------------------------
-- GENERATED FILEOBJECTS: 
-------------------------------
{
  'GENERATED JAVA FILE OBJECTS' : 'No files were generated !!!',
  'GENERATED FILE OBJECTS' :'No files were generated !!!'
}
-------------------------------
-- COMPILE TEST CONFIGURATION: 
-------------------------------
CompileTestConfiguration{

	compilerOptions=[],
	sourceFiles=[io.toolisticon.cute.JavaFileObjectUtils$JavaSourceFromResource[resource:///api_service/TestcaseInvalidUseWithInterfaceNotExtendingApiService.java]],
	 processors=[],
	 processorTypes=[class br.com.c8tech.hawkx.dev.apt.processors.http.ApiServiceProcessor],
	 processorsWithExpectedExceptions=[],
	 expectedThrownException=null,
	 modules=null,
	 compilationShouldSucceed=false,
	 compilerMessageChecks=[],
	 generatedJavaFileObjectChecks=[],
	 generatedFileObjectChecks=[],
	 passInConfiguration=null
}
	at io.toolisticon.cute.extension.plainjava.AssertionErrorAssertion.fail(AssertionErrorAssertion.java:11)
	at io.toolisticon.cute.impl.CompileTest.executeTest(CompileTest.java:170)
	at io.toolisticon.cute.CompileTestBuilder$BasicBuilder.executeTest(CompileTestBuilder.java:527)
	at br.com.c8tech.hawkx.dev.apt.processors.http.ApiServiceAnnotationProcessorTest.test_processingShouldntSucceesWithPlainInterfacesNotExtendingApiService(ApiServiceAnnotationProcessorTest.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by cvgaviao** [comment]
> So please remove the annotation processors from unit test configuration that you don't expect to be called, since they doesn't change test outcome in any way.

Yep, creating another instance of CompilationTestBuilder without adding a processor resolved the issue. :)
```
  @Test
  void test_processingShouldntSucceesWithPlainInterfacesNotExtendingApiService() {
    CompileTestBuilder.CompilationTestBuilder compileTestBuilder2 = CompileTestBuilder
                                                                                      .compilationTest();

    compileTestBuilder2
                       .addSources("api_service/TestcaseInvalidUseWithInterfaceNotExtendingApiService.java")
                       .compilationShouldFail()
                       .executeTest();
  }
```

**Comment by cvgaviao** [comment]
I forgot to say. thanks for your quick support, and mainly for the very useful projects ;)

**Comment by tobiasstamann** [comment]
Yes, the main issue was, that the error that you have expected comes from Java itself because of the broken contract. 

The processor phase hasn't been started then. 

Thanks by the feedback. Hope you like those processor frameworks and that they will help you on your way :)

Please contact me if you have any additional questions or feature requests.
