### ISSUE TITLE
How to assert "No files were generated !!!"

### ISSUE THREAD

**Issue by verhasi** [toolisticon/cute#82]
As a newcomer to the CUTE and going in a TDD-like style my first test should be a successful compile and no file is generated. Here is the test in progress
```
package guru.mocker.annotation.mixin.test;

import guru.mocker.annotation.mixin.MixinProcessor;
import io.toolisticon.cute.Cute;
import org.junit.jupiter.api.Test;

public class BlackBoxTest
{
    @Test
    void mixinProcessor_noInterfaceAndNoConstructorParameter_noParentGenerated()
    {
        Cute.blackBoxTest().given().processor(MixinProcessor.class)
                .andSourceFiles("/guru/mocker/annotation/mixin/test/mixin/NoInterfaceNoConstructorParameter.java")
                .whenCompiled()
                .thenExpectThat()
                .compilationSucceeds()
                .andThat()
                .compilerMessage()
                .ofKindWarning()
                .contains("No files were generated !!!")
                .executeTest();
    }
}
```
and the run result
```
java.lang.AssertionError: Haven't found expected message string '[No files were generated !!!]' of kind WARNING!

-------------------------------
-- WARNING MESSAGES: 
-------------------------------
[1]'warning: Supported source version 'RELEASE_8' from annotation processor 'io.toolisticon.cute.AnnotationProcessorWrapper' less than -source '21''

-------------------------------
-- GENERATED FILEOBJECTS: 
-------------------------------
{
  'GENERATED JAVA FILE OBJECTS' : [
    'mem://SOURCE_OUTPUT/Object.java' := '/Users/istvanverhas/IdeaProjects/Mixin/target/cute_failingUnitTests/xaurokxtjz/Object.java', 
    'mem://CLASS_OUTPUT/TestClass.class' := '/Users/istvanverhas/IdeaProjects/Mixin/target/cute_failingUnitTests/xaurokxtjz/TestClass.class', 
    'mem://CLASS_OUTPUT/Object.class' := '/Users/istvanverhas/IdeaProjects/Mixin/target/cute_failingUnitTests/xaurokxtjz/Object.class', 
  ],
  'GENERATED FILE OBJECTS' :'No files were generated !!!'
}
-------------------------------
-- COMPILE TEST CONFIGURATION: 
-------------------------------
{\ntestType = BLACK_BOX,
compilationSucceeded = true,
processors = [class guru.mocker.annotation.mixin.MixinProcessor],
compilerOptions = [],
getPassInType = null,
fileObjectChecks = [],
modules = [],
getGeneratedClassesTest = [],
getExceptionIsThrown = null,
sourceFiles = [io.toolisticon.cute.JavaFileObjectUtils$JavaSourceFromResource[resource:///guru/mocker/annotation/mixin/test/mixin/NoInterfaceNoConstructorParameter.java]],
javaFileObjectChecks = [],
passInConfiguration = null,
unitTest = null,
compilerMessageChecks = [{\nwithLocale = null,
getSearchString = [No files were generated !!!],
atColumn = null,
atSource = null,
getComparisonType = CONTAINS,
getKind = WARNING,
atLine = null,
}],
}

	at io.toolisticon.cute.extension.plainjava.AssertionErrorAssertion.fail(AssertionErrorAssertion.java:11)
	at io.toolisticon.cute.CompileTest.executeTest(CompileTest.java:199)
	at io.toolisticon.cute.CuteApi$ExecuteTestCommand.myCommand(CuteApi.java:1229)
	at io.toolisticon.cute.Cute$CompilerTestExpectAndThatInterfaceImpl.executeTest(Cute.java:1985)
	at guru.mocker.annotation.mixin.test.BlackBoxTest.mixinProcessor_noInterfaceAndNoConstructorParameter_noParentGenerated(BlackBoxTest.java:21)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)


Process finished with exit code 255
```
so it is not a message from the compiler as I have tried it with error and warning as well. What else can I test against?

**Comment by tobiasstamann** [comment]
At the moment there is no dedicated check if no files have been generated.

I decided against implemented it because usually when you test annotation processors you know what files are expected to be generated by the processor  or in case of an error must not be generated by it. That's why there are currently just checks for the presence or  non presence of specific generated files. 

So currently you can do the following:
`        Cute.blackBoxTest().given().processors(YourProcessor.class)
                .andSourceFiles("yourSource.java")
                .whenCompiled().thenExpectThat()
                        .compilationSucceeds()
                                .andThat().generatedSourceFile("io.toolisticon.YourGeneratedClass").doesntExist()
                        .executeTest();`

But i can add it if you really need it.

**Comment by tobiasstamann** [comment]
Additionally there's not one single location where (source-)files will be generated to. 
Source files will usually be written to StandardLocation.SOURCE_OUTPUT and resource files to CLASS_OUTPUT which is also used by the compiler for class output. So at least for the CLASS_OUTPUT we cannot distinct if a file was generated or not.

For SOURCE files it would be possible. I am currently adding the method to check it

**Comment by tobiasstamann** [comment]
Hi,

Your processor seems  to have generated a source file named Object.java which is compiled afterwards.

About the debugging output of Cute:
Usually the compiler distincts between java related files (JavaFileObject) and all other kind of resources (FileObject) These are handled internally by two distinct FileManagers by the compiler. That's why the debug output  shows the two sets GENERATED JAVA FILE OBJECTS and GENERATED FILE OBJECTS.

The String "No files were generated !!!" just belongs to the debug output and cannot be checked with compiler message checks.

I will add checks for emptiness of the GENERATED FILE OBJECTS file manager and if no generated SOURCE files exist in SOURCE_OUTPUT Standard location.

**Comment by verhasi** [comment]
Just a joke:
Is it executeTest or exeCuteTest?
:)

**Comment by tobiasstamann** [comment]
But this has one drawback, you will loose debug output in case of failing test.

Alternatively i could provide a fluent api method that passes in the compiler outcome and can be used for checks. 
This would be kind of similar to cute's unit tests.

**Comment by tobiasstamann** [comment]
The main advantage is that you can still use any kind of assertion framework and that those check are wrapped by cute. In case of AssertionError it will automatically print out all debug output and writes all generated files from mem to disk which is pretty nice for debugging.

**Comment by verhasi** [comment]
What protects you from gathering the debug output during the execution and provide them in the TestExecutionResult?

**Comment by verhasi** [comment]
The generic assertion fluent step wrapping is a good idea. The lambda/consumer's parameter could be the TestExecutionResult. It could be after the executeTest step, couldn't be?

**Comment by tobiasstamann** [comment]
And how a unit test then could look like: https://github.com/toolisticon/cute/blob/feature/manualAssrtions/cute/src/test/java/io/toolisticon/cute/CuteTest.java

**Comment by verhasi** [comment]
I would prefer DoManualAssertion (single assertion in one step), which could be repeated to make it easier to identify which assertion failed. So the modified interface would be

```
public interface DoManualAssertion {

        DoManualAssertion doManualAssertion(ManualAssertion manualAssertion);

    }
```

**Comment by tobiasstamann** [comment]
There's usually no need to have that loop. The AssertionError refers to the failing assertion statement, i.e:
java.lang.AssertionError: Should be true

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:26)
	at io.toolisticon.cute.CuteTest.lambda$test_UnitTest_successfulCompilation_build$0(CuteTest.java:67)
	at io.toolisticon.cute.CuteApi$DoManualAssertionsImpl.doManualAssertions(CuteApi.java:1267)
	at io.toolisticon.cute.CuteTest.test_UnitTest_successfulCompilation_build(CuteTest.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

So you can usually directly identify the line that produced the assertion :)

**Comment by tobiasstamann** [comment]
So basically it doesn't really differ from "normal" assertions outside the lambda.

**Comment by tobiasstamann** [comment]
I have added now the access to the Filemanager as well. But it's not optimal now since reading a file needs try/catch block to work.

@verhasi : Can you please check if something is missing or if you think that additional methods are needed?

**Comment by verhasi** [comment]
Nice progress in one day. I have tried it and working almost perfectly. It does what we meant but the debug output is missing. The reason is the assert throws java.lang.AssertionError (->Error->Throwable) and you catch Exception not in the hierarchy.

**Comment by tobiasstamann** [comment]
You are right, i had it working and destroyed it again. But it's fixed now.

I will add some additional methods for doing files checks like location / packagename / classname / byte[] content.

**Comment by tobiasstamann** [comment]
I have added some more features now like access to ClassLoader for generated classes and have added some convenience methods. 
Nevertheless, it is still not fully tested and needs proper Javadoc.

I guess it will be finished and released on Monday :)

**Comment by tobiasstamann** [comment]
The release has been done. It will be available later today in maven central (approx 6-8 hours).

@verhasi : Please check if provided features are sufficient and file/reopen an issue if something still has to be added.
